apiVersion: v1
kind: Secret
metadata:
  name: traefik-default-tls
  namespace: traefik
  annotations:
    kots.io/exclude: 'repl{{ not (ConfigOptionEquals "tls_mode" "manual") }}'
type: kubernetes.io/tls
data:
  tls.crt: 'repl{{ ConfigOption "tls_cert" }}'
  tls.key: 'repl{{ ConfigOption "tls_key" }}'
