apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: playball-exe
spec:
  chart:
    name: playball-exe
    chartVersion: 0.1.0
  releaseName: playball-exe
  helmUpgradeFlags:
    - --timeout
    - 10m
  builder:
    nextauth:
      secret: placeholder
  values:
    image:
      registry: 'repl{{ ReplicatedImageRegistry "images.emosbaugh.be" }}'
      repository: 'repl{{ ReplicatedImageRepository "docker.io/replemos/playball.exe" }}'
    replicated:
      image:
        registry: 'repl{{ ReplicatedImageRegistry "images.emosbaugh.be" }}'
        repository: 'repl{{ if IsAirgap }}repl{{ ReplicatedImageRepository "library/replicated-sdk-image" }}repl{{ else }}library/replicated-sdk-image{{ end }}'
    postgresql:
      enabled: repl{{ ConfigOptionEquals "postgresql_enabled" "1" }}
      image:
        registry: 'repl{{ ReplicatedImageRegistry "images.emosbaugh.be" }}'
        repository: 'repl{{ ReplicatedImageRepository "registry-1.docker.io/bitnami/postgresql" }}'
    externalDatabase:
      url: 'repl{{ ConfigOption "external_postgres_url" }}'
    redis:
      enabled: repl{{ ConfigOptionEquals "redis_enabled" "1" }}
      image:
        registry: 'repl{{ ReplicatedImageRegistry "images.emosbaugh.be" }}'
        repository: 'repl{{ ReplicatedImageRepository "registry-1.docker.io/bitnami/redis" }}'
      replica:
        replicaCount: 1
    externalRedis:
      url: 'repl{{ ConfigOption "external_redis_url" }}'
    nextauth:
      secret: 'repl{{ ConfigOption "nextauth_secret" }}'
      url: 'repl{{ print "https://" (or (ConfigOption "hostname") "localhost") }}'
    ingress:
      enabled: true
      className: traefik
      hostname: 'repl{{ ConfigOption "hostname" }}'
    aiCommentary:
      provider: 'repl{{ ConfigOption "ai_provider" }}'
      openaiApiKey: 'repl{{ ConfigOption "openai_api_key" }}'
      anthropicApiKey: 'repl{{ ConfigOption "anthropic_api_key" }}'
