apiVersion: v2
name: playball-exe
description: Helm chart for deploying the playball.exe baseball game
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: postgresql
    version: "18.5.15"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "25.3.9"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: replicated-sdk
    version: "1.0.0-beta.33"
    repository: oci://registry.replicated.com/library
    alias: sdk
    condition: sdk.enabled
