{{- if and .Values.certManager.enabled (eq .Values.certManager.mode "lets_encrypt_dns01") }}
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-route53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  access-key-id: {{ .Values.certManager.acme.dns01.route53.accessKeyId | quote }}
  secret-access-key: {{ .Values.certManager.acme.dns01.route53.secretAccessKey | quote }}
{{- end }}
