apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "playball-exe.fullname" . }}
  labels:
    {{- include "playball-exe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "playball-exe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "playball-exe.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - node_modules/prisma/build/index.js
            - migrate
            - deploy
          envFrom:
            - secretRef:
                name: {{ include "playball-exe.fullname" . }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "playball-exe.fullname" . }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
