apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playball-exe.fullname" . }}-support-bundle
  labels:
    {{- include "playball-exe.labels" . | nindent 4 }}
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: {{ include "playball-exe.fullname" . }}
    spec:
      collectors:
        - logs:
            name: app
            namespace: {{ .Release.Namespace }}
            selector:
              - app.kubernetes.io/name=playball-exe
            limits:
              maxAge: "720h"
              maxLines: 10000
        - logs:
            name: postgres
            namespace: {{ .Release.Namespace }}
            selector:
              - app.kubernetes.io/name=postgresql
              - app.kubernetes.io/instance={{ .Release.Name }}
            limits:
              maxAge: "720h"
              maxLines: 10000
        - logs:
            name: redis
            namespace: {{ .Release.Namespace }}
            selector:
              - app.kubernetes.io/name=redis
              - app.kubernetes.io/instance={{ .Release.Name }}
            limits:
              maxAge: "720h"
              maxLines: 10000
        - logs:
            name: sdk
            namespace: {{ .Release.Namespace }}
            selector:
              - app.kubernetes.io/name={{ .Values.replicated.nameOverride | default "replicated" }}
              - app.kubernetes.io/instance={{ .Release.Name }}
            limits:
              maxAge: "720h"
              maxLines: 10000
        - http:
            name: app-healthz
            get:
              url: http://{{ include "playball-exe.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/api/healthz
      analyzers:
        - textAnalyze:
            checkName: App Health
            fileName: http/app-healthz/response.json
            regex: '"status":"ok"'
            outcomes:
              - pass:
                  when: "true"
                  message: Application is healthy
              - fail:
                  when: "false"
                  message: Application is not healthy
