{{- include "playball-exe.validateTls" . -}}
{{- if and .Values.tls.enabled (eq .Values.tls.mode "manual") .Values.tls.manual.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playball-exe.fullname" . }}-tls
  labels:
    {{- include "playball-exe.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.manual.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.manual.key | b64enc | quote }}
{{- end }}
