name: Build and Test

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/docker-publish.yml
    with:
      tag: pr-${{ github.event.pull_request.number }}
    secrets: inherit

  e2e:
    needs: build
    uses: ./.github/workflows/e2e.yml
    with:
      image-tag: pr-${{ github.event.pull_request.number }}
    secrets: inherit
